version: '3'
services:
  ruby:
    image: ruby:2.6.4
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/usr/src/app"
    working_dir: /usr/src/app
